# Generated by Django 5.1.1 on 2024-10-12 14:57

import django.core.validators
import participant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='cin',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Le CIN doit contenir exactement 8 chiffres.', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[participant.models.validate_email_domain]),
        ),
    ]
