# Generated by Django 4.2.16 on 2024-10-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_titre'),
        ('conference', '0002_conference_end_date_conference_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='category',
            field=models.ForeignKey(choices=[('dev personnel', 'Developement'), ('sante', 'sante'), ('education', 'education')], on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
