# Generated by Django 5.1.1 on 2024-10-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('confirmée', 'Confirmée'), ('non confirmée', 'Non Confirmée')], default='non confirmée', max_length=20),
        ),
    ]
